### ISSUE TITLE
Export of F4 versions no longer works

### ISSUE THREAD

**Issue by awoods** [fcrepo-exts/fcrepo-import-export#155]
As of: https://github.com/fcrepo-exts/fcrepo-import-export/commit/9b1b03c72e76e7ce2a4aeae98ed3ecbe053cd3d0
..the export of F4 versions no longer works. This is likely due to the fact that the logic was changed in the above commit to look for the "timemap Link header", which does not exist in F4. Resources in F4 indicate that they are versioned by including the following RDF triple:
```
<> fedora:hasVersions <resource>/fcr:versions
```

**Comment by whikloj** [comment]
Based on the discussion in the linked PR and the information on the [Migrate to Fedora 6](https://wiki.lyrasis.org/display/FEDORA6x/Migrate+to+Fedora+6) documentation, you need to export your Fedora 4 using an older version of the fcrepo-import-export tool (specifically `0.3.0`). So I'm closing this issue.

**Comment by cjcolvar** [comment]
FWIW I was able to export my Fedora 4 test instance (no acls or versions) using the latest version of fcrepo-import-export tool (1.2.0) and get an identical export when I added the `--membership` flag.

Command with 0.3.0:
```
java -jar fcrepo-import-export-0.3.0.jar -b --dir F4_export --user fedoraAdmin:fedoraAdmin --mode export --resource http://localhost:8080/fedora/rest --binaries
```
Command with 1.2.0:
```
java -jar fcrepo-import-export-1.2.0.jar -b --dir F4_export --user fedoraAdmin:fedoraAdmin --mode export --resource http://localhost:8080/fedora/rest --binaries --membership
```
